fix: module not found in @scaleleap/amazon-marketplaces
ScaleLeap/amazon-advertising-api-sdk pull request #1025
Opened 2024-08-13 14:40 UTC by nguyentoanit

There was a bug in the `@scaleleap/amazon-marketplaces` package.
Need to update to the latest version to fix this

Closes #1023

2024-08-13 19:09 UTC, moltar requested changes

2024-08-13 19:09 UTC, moltar commented on package.json
> +    "@scaleleap/amazon-marketplaces": "18.0.1",
Probably should be a caret ^18

2024-09-04 06:31 UTC, jiangdi0924 commented
Could you please let me know when this can be merged into the main branch? Thank you.

2024-09-04 10:08 UTC, moltar commented
@nguyentoanit Please wrap this up asap.

2024-09-11 04:54 UTC, merged

2024-09-11 05:11 UTC, nguyentoanit commented
@moltar @jiangdi0924 : We got an issue when release 🐞: https://github.com/ScaleLeap/amazon-advertising-api-sdk/actions/runs/10805243502/job/29972026362

I'm trying to fix it soon.